-- SELECT * FROM user_actions;


SELECT '7' AS MONTH ,COUNT(DISTINCT(U1.USER_ID)) AS MONTHLY_ACTIVE_USERS
FROM
USER_ACTIONS AS U1
INNER JOIN
USER_ACTIONS AS U2
ON U1.USER_ID = U2.USER_ID
AND EXTRACT(MONTH FROM U1.EVENT_DATE) = '6' AND EXTRACT(MONTH FROM U2.EVENT_DATE) = '7';
-- GROUP BY U1.USER_ID;